### ISSUE TITLE
Demo250 not updated

### ISSUE THREAD

**Issue by SteveLasker** [rgardler/AzureDevTestDeploy#11]
https://github.com/rgardler/AzureDevTestDeploy/tree/master/demo/demo250_automated_deployment

for Dev Machine Configuration, the script calls for prepare-dev.sh, however the repo doesn't have a -dev.sh file

For the novice git bash user, it's not clear the git clone command pulls into the current directory, as opposed to the github configured default location. Should qualify to switch to a directory you want to put your contents in

**Comment by rgardler** [comment]
Thanks for picking up the out of sync instructions. Fixing.

Since GitHub != git I'm not going to qualify git behavior based on a certain type of user. There are many other tools that use Git and we can't possibly customize the instructions for every type of user. I'm sure needing to do a mv is not problematic.
